Remove the non-existent default title feature
I see this was copypasted from Iron Router's package documentation, but (sadly) it's not available in Flow Router which doesn't provide such api and returns "TypeError: FlowRouter.configure is not a function" message.